// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? "";

export const hasSupabaseConfig = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

const resolvedSupabaseUrl = hasSupabaseConfig ? SUPABASE_URL : "https://placeholder.supabase.co";
const resolvedSupabaseKey = hasSupabaseConfig ? SUPABASE_PUBLISHABLE_KEY : "placeholder-key";

// Singleton client — never recreated between hot-reloads or SPA navigations.
export const supabase = createClient<Database>(resolvedSupabaseUrl, resolvedSupabaseKey, {
  auth: {
    // Store session in localStorage so it survives F5 / tab close / re-open.
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    // Automatically refresh the access token before it expires (~1 min before exp).
    autoRefreshToken: true,
    // Detect session from URL hash on OAuth callback pages.
    detectSessionInUrl: true,
  },
});
