// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? '';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set in your .env file.'
  );
}

// Singleton client — never recreated between hot-reloads or SPA navigations.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Store session in localStorage so it survives F5 / tab close / re-open.
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    persistSession: true,
    // Automatically refresh the access token before it expires (~1 min before exp).
    autoRefreshToken: true,
    // Detect session from URL hash on OAuth callback pages.
    detectSessionInUrl: true,
  },
});
